### ISSUE TITLE
Icon in tab is displayed wrong on MacOS X

### ISSUE THREAD

**Issue by HonkXL** [ric2016/relatives_with_hooks#1]
I am using Mac OS X and I was used that in the title tab there is a box or a unreadable sign. Today I looked my webtrees on a Windows PC and wondered that this is no box, but a nice icon.

Here a screenshot. Left side is Firefox on PC, right side is Firefox on Mac OS X.

<img width="998" alt="title" src="https://user-images.githubusercontent.com/16715040/52746492-ebb27900-2fe1-11e9-888c-080dc6db78b9.png">

and here on Safari for Mac OS:

<img width="506" alt="title-safari" src="https://user-images.githubusercontent.com/16715040/52746557-1270af80-2fe2-11e9-92f9-6c775aeb94fe.png">

And here on Chrome for Mac OS:

<img width="485" alt="chrome" src="https://user-images.githubusercontent.com/16715040/52746632-4055f400-2fe2-11e9-9663-d9773517a779.png">

**Comment by HonkXL** [comment]
Can you make the icon configurable?
I have both Fact pages active - standard for visitors and gov for Users.

Webtrees 2.0 is not usable for me, because the new UI is a pain when you are used to work with multiple windows... but this is off topic here.

**Comment by ric2016** [comment]
> Can you make the icon configurable?

Tab names in general could be made configurable - But how to handle the translations? Using a different icon may not work in all fonts either.

> I have both Fact pages active - standard for visitors and gov for Users.

I see - what actually would help here are access levels for the hooks. Then you could use a single tab, which would also avoid the tab duplication for users. I'll think about this.

> Webtrees 2.0 is not usable for me

Well, it's still alpha. I agree about the new layout, and I hope this will be addressed (via specific themes or other mechanisms).

**Comment by ric2016** [comment]
2.x version of the module has access levels, so there is no need for separate tabs any more (gov enhancement can be hidden from visitors via access levels).
(1.x version will only receive bug fies from now on - no further enhancements are planned)
